### ISSUE TITLE
Suggestion for eSteem Logo

### ISSUE THREAD

**Issue by FlashGordon95** [feruzm/esteem#2]
Current eSteem logo looks really nice. I noticed some users were not too happy about the Steem logo being turned around so I was thinking a good way to satisfy everyone might be to introduce a logo with has both the 'e' and the steem logo in it.
I have put together a small mockup of what this would look like. 
![esteem](https://cloud.githubusercontent.com/assets/11082710/17773421/3f319e44-6546-11e6-86ab-75f7ba98d557.png)  

This is a very quickly done mockup so it won't look amazing however with some touchup and perhaps incorporating the blue circle from the current eSteem logo I think it could look really nice.

**Comment by feruzm** [comment]
Thank you Ryan! I do think logo needs an update. But we can't use Steem logo directly as it is stated in [Terms of Use](http://steemit.com/tos.html). I like the idea, let's brainstorm this and see what comes out...

**Comment by FlashGordon95** [comment]
One possible solution would be to try and seek permission for use of the steem logo from ned or dan, which would definitely put this app a step ahead of Steemy. I'm thinking this is a viable option given the project is open source, we will definitely not get endorsement but we might as least get permission for use of the name+logo.  If permission can't be gotten via those means then well just need a bit of creativity

**Comment by feruzm** [comment]
I have contacted Ned before and he said we can use it, but there is no certain way to handle this being both projects opensource but Steemit trademark with its logo cannot be used directly. The main reason for change was because Google play suspended initial app which was named Steem Mobile due to its use if Steemit logo directly, I thought it is good idea to have new brand and name for the app. Since app mainly uses Steem as oppose to Steemit.com. Yes, as for creativity we can try different designs. Brand or App name **eSteem** - means esteem as well as e-steem (electronic steem just like email - Electronic mail).

**Comment by FlashGordon95** [comment]
Thats one of the main reasons I liked the name so much , has a double purpose and if I'm not mistaken the original name for steem stems from the word esteem so its a good fit in all aspects.  

I wanted to ask also do you think that implementing some sort of encryption for the user login details would greatly affect the performance of the app ? While I was still working on my own steem repo I was thinking of implementing [JsAES](http://point-at-infinity.org/jsaes/) to encrypt stored data such as loginData and decrypt.

**Comment by feruzm** [comment]
Thanks! Not sure about performance impact, but it sure adds up some time delay. Because right now, block times are I think 2-3 sec which requires app to send request after vote or comment. Which means user is already waiting 2-3 seconds before seeing they actually voted on post. Adding encryption is not difficult, but decryption on every operation seem like adding extra task. Beside mobile devices are less prone for hacks. User is also warned during login that they have to make sure their phone is secure. That doesn't mean it cannot be secure, of course, I am thinking about encryption in long run, in terms like pin code encryption, where user confirms transfer or other operations with extra pin code. I am open to discussions on that as well.

**Comment by FlashGordon95** [comment]
I agree with you , adding in an extra action on every operation will add some delay. I would say it is definitely one for the roadmap but atm the main focus definitely should be on UX and a fair warning can definitely suffice for the early days of the app!

**Comment by FlashGordon95** [comment]
Perhaps one possible implementation would be a user enabled feature in the 'settings' , would allow the add a layer of security to their account via a passcode (or touch id/fingerprint if available). Disabled by default it would give some more security conscious people, or users of a company/shared phone to still access the app with confidence.

**Comment by feruzm** [comment]
yes, touch id is actually great idea

**Comment by FlashGordon95** [comment]
I could try to implement it into a pull request. I was thinking of doing something similar for TOTP app that I am working on. Can I ask are you using the Ionic 1.X or 2 Beta for this ?

**Comment by feruzm** [comment]
Sure, feel free to join, let me know more how it would work. It is Ionic 1.x.

**Comment by FlashGordon95** [comment]
Initial thoughts would be having some sort of toggle  in the settings page. When enabled the user can either be asked to set up a pin code (might be best option) or they can use their phone passcode. 
Touch ID and Android fingerprint would be handled with cordova touchID and we would need to pick a library for android fingerprint as there are many. 
We show a prompt for Touch ID/Android fingerprint with the secondary option for using the backup passcode (the libraries handle the prompt itself).

**Comment by FlashGordon95** [comment]
Ionic 1 is no problem I was using Ionic 2 for my repo but to be honest it did provide some problems when using certains things like InnerHTML.

**Comment by feruzm** [comment]
I see, do you have any link to your project? I am thinking change on settings page as list that opens up different settings. For example: Server, Notifications, Security, etc. Will work on them in coming days... Though there are couple things I am currently busy researching Steem and Steemit.com code for making posts. With recent changes comments working better now and pushed 1.1.2 version to Google Play. Do you have experience with iOS App store?

**Comment by feruzm** [comment]
It is taking almost 2 weeks now to review very first version 1.0.0 and after that I have improved app a lot, UX, functionality, etc. But I don't want to delay review by pushing new release again.

**Comment by FlashGordon95** [comment]
Here is my app : https://github.com/FlashGordon95/steemit-mobile-ionic
It is similar however it lacks a lot of the features your does, mostly because I started mine without the knowledge someone was also working on one. 

By a list do you mean something like a drop down list of setting that expands in the sidemenu or do you mean a entire separate page with sections for each of these options you mention ? 

I have not made any apps for the iOS app store yet althought I do have some experience helping colleagues prepare their app submission for review. I actually work part-time for Apple at the moment so one thing I will need to outline is that if we are to work together and maybe one day make a github org then I would need you to actually release the app packages to the stores as until I finish my contract here i am not allowed to do so. That being said I can definetly help the app meet any guidelines that it could be failing on.

**Comment by FlashGordon95** [comment]
Yes i think it is important not to push too many releases too early. Pushing too many releases will cause a feature 'creep' its better to go slow and steady with it.

**Comment by feruzm** [comment]
yes, that's why Android is getting more frequent updates and can get more feedback before iOS second release can be sent to review.
I have pushed version 1.0.0 to get feeling of if Apple review was to done successful then would push another update shortly after. As for Settings, no it is just a list that opens up separate pages or popups. Not 100% yet, as you can see I am flowing with user experience and listening multiple places where user give feedback. I choose GPL license so it shouldn't be problem for future of the project, though I will review this again in more details. I have mentioned to Apple review team that I will be the one responsible to handle iOS releases. But considering project is opensource, any fork of the project needs to be under same license and should referenced to source code.

**Comment by feruzm** [comment]
Your app is in ionic 2.x that's good. I think you can still work on it, as far as I heard ionic 2.x has some advantages over ionic 1.x. You are welcome to use part of code from this repo as well.

**Comment by FlashGordon95** [comment]
iOS release review usually takes a long time, mostly just becuase of the sheer amount of apps coming through to the review team. 
To be honest I think a good idea would be to use my app as a lite version of eSteem. 
When I was designing my app I wanted to focus on delivering a minimal look while trying not to use too much data or battery. 
While your app is aiming to provide a full fledged user enviroment, mine could provide smaller view with less functionality simply intended to be a reader app. 
Do you have a rocket.chat or an email I could contact you at?

**Comment by feruzm** [comment]
yes, please lets get contacted on steemit.chat, find good.karma
